export const careerCategories = [
  {
    id: 'engineering',
    name: 'Engineering',
    count: '42 Career Paths',
    icon: 'precision_manufacturing',
    description: 'Build solutions across software, mechanical systems, electronics, civil infrastructure, robotics, and emerging technologies.',
    popularPaths: ['Software', 'Mechanical', 'Civil'],
    paths: [
      'Software Engineer',
      'Computer Hardware Engineer',
      'Data Engineer',
      'AI/ML Engineer',
      'Cybersecurity Engineer',
      'Cloud Engineer',
      'DevOps Engineer',
      'Civil Engineer',
      'Structural Engineer',
      'Environmental Engineer',
      'Transportation Engineer',
      'Geotechnical Engineer',
      'Mechanical Engineer',
      'Automobile Engineer',
      'Aerospace Engineer',
      'Robotics Engineer',
      'Manufacturing Engineer',
      'Industrial Engineer',
      'Electrical Engineer',
      'Electronics Engineer',
      'Telecommunication Engineer',
      'Instrumentation Engineer',
      'Power Systems Engineer',
      'Renewable Energy Engineer',
      'Chemical Engineer',
      'Petroleum Engineer',
      'Biomedical Engineer',
      'Biotechnology Engineer',
      'Agricultural Engineer',
      'Marine Engineer',
      'Mining Engineer',
      'Metallurgical Engineer',
      'Materials Engineer',
      'Mechatronics Engineer',
      'Nanotechnology Engineer',
      'Food Technology Engineer',
      'Textile Engineer',
      'Nuclear Engineer',
      'Quality Assurance Engineer',
      'Product Design Engineer',
      'Safety Engineer',
      'Systems Engineer'
    ]
  },
  {
    id: 'medical',
    name: 'Medical',
    count: '28 Career Paths',
    icon: 'medical_services',
    description: 'Explore clinical care, diagnostics, research, public health, allied health, and healthcare management careers.',
    popularPaths: ['MBBS', 'Nursing', 'Pharmacy'],
    paths: [
      'Doctor',
      'Surgeon',
      'Dentist',
      'Nurse',
      'Pharmacist',
      'Physiotherapist',
      'Veterinarian',
      'Medical Lab Technologist',
      'Radiologist',
      'Anesthesiologist',
      'Cardiologist',
      'Dermatologist',
      'Pediatrician',
      'Psychiatrist',
      'Psychologist',
      'Nutritionist',
      'Optometrist',
      'Occupational Therapist',
      'Speech Therapist',
      'Public Health Specialist',
      'Biomedical Scientist',
      'Clinical Researcher',
      'Paramedic',
      'Hospital Administrator',
      'Forensic Medical Expert',
      'Homeopathy Doctor',
      'Ayurveda Doctor',
      'Medical Writer'
    ]
  },
  {
    id: 'arts',
    name: 'Arts',
    count: '35 Career Paths',
    icon: 'palette',
    description: 'Discover creative paths in design, media, writing, fine arts, animation, performing arts, and cultural industries.',
    popularPaths: ['Design', 'Media', 'Fine Arts'],
    paths: [
      'Graphic Designer',
      'UI/UX Designer',
      'Fashion Designer',
      'Interior Designer',
      'Animator',
      'Illustrator',
      'Fine Artist',
      'Photographer',
      'Film Director',
      'Video Editor',
      'Content Writer',
      'Copywriter',
      'Journalist',
      'Author',
      'Screenwriter',
      'Actor',
      'Musician',
      'Dancer',
      'Theatre Artist',
      'Art Director',
      'Creative Director',
      'Game Artist',
      'Product Designer',
      'Architect',
      'Museum Curator',
      'Art Therapist',
      'Digital Marketer',
      'Social Media Manager',
      'Event Manager',
      'Public Relations Specialist',
      'Language Translator',
      'Linguist',
      'Historian',
      'Archaeologist',
      'Sociologist'
    ]
  },
  {
    id: 'commerce',
    name: 'Commerce',
    count: '19 Career Paths',
    icon: 'trending_up',
    description: 'Compare careers in finance, accounting, business analytics, economics, entrepreneurship, and management.',
    popularPaths: ['CA', 'Finance', 'Business'],
    paths: [
      'Chartered Accountant',
      'Company Secretary',
      'Cost Accountant',
      'Investment Banker',
      'Financial Analyst',
      'Business Analyst',
      'Accountant',
      'Auditor',
      'Tax Consultant',
      'Bank Manager',
      'Stockbroker',
      'Insurance Advisor',
      'Marketing Manager',
      'Human Resources Manager',
      'Operations Manager',
      'Entrepreneur',
      'Economist',
      'Actuary',
      'Management Consultant'
    ]
  },
  {
    id: 'government',
    name: 'Government',
    count: '54 Career Paths',
    icon: 'account_balance',
    description: 'Prepare for civil services, defense, public administration, policy, law enforcement, and public sector opportunities.',
    popularPaths: ['UPSC', 'Defense', 'Public Sector'],
    paths: [
      'IAS Officer',
      'IPS Officer',
      'IFS Officer',
      'IRS Officer',
      'Defense Officer',
      'Army Officer',
      'Navy Officer',
      'Air Force Officer',
      'Police Officer',
      'Railway Officer',
      'Bank PO',
      'SSC Officer',
      'State Civil Service Officer',
      'Judge',
      'Public Prosecutor',
      'Government Teacher',
      'Professor',
      'Scientist',
      'Forest Officer',
      'Customs Officer',
      'Income Tax Officer',
      'Public Sector Engineer',
      'Administrative Assistant',
      'Clerk',
      'Data Entry Operator',
      'Librarian',
      'Diplomat',
      'Policy Analyst',
      'Urban Planner',
      'Social Welfare Officer',
      'Agricultural Officer',
      'Food Safety Officer',
      'Labour Officer',
      'Excise Officer',
      'Intelligence Officer',
      'Coast Guard Officer',
      'Postal Officer',
      'Municipal Officer',
      'Public Health Officer',
      'Election Officer',
      'Revenue Officer',
      'Transport Officer',
      'Legal Officer',
      'Accounts Officer',
      'Audit Officer',
      'Statistical Officer',
      'Information Officer',
      'Planning Officer',
      'Disaster Management Officer',
      'Women and Child Development Officer',
      'Rural Development Officer',
      'Panchayat Officer',
      'Foreign Service Assistant',
      'Research Officer'
    ]
  },
  {
    id: 'entrepreneurship',
    name: 'Entrepreneurship',
    count: '12 Programs',
    icon: 'rocket_launch',
    description: 'Learn how founders identify ideas, validate markets, build teams, raise capital, and launch scalable ventures.',
    popularPaths: ['Startup', 'Product', 'Venture Building'],
    paths: [
      'Startup Founder',
      'Small Business Owner',
      'Product Founder',
      'Social Entrepreneur',
      'E-commerce Entrepreneur',
      'Franchise Owner',
      'Consultant',
      'Creator Entrepreneur',
      'Tech Entrepreneur',
      'Food Business Founder',
      'Education Business Founder',
      'Venture Builder'
    ]
  }
];

export const engineeringColleges = [
  { name: 'IIT Bombay', city: 'Mumbai', state: 'Maharashtra', type: 'IIT' },
  { name: 'IIT Delhi', city: 'New Delhi', state: 'Delhi', type: 'IIT' },
  { name: 'IIT Madras', city: 'Chennai', state: 'Tamil Nadu', type: 'IIT' },
  { name: 'IIT Kanpur', city: 'Kanpur', state: 'Uttar Pradesh', type: 'IIT' },
  { name: 'IIT Kharagpur', city: 'Kharagpur', state: 'West Bengal', type: 'IIT' },
  { name: 'IIT Roorkee', city: 'Roorkee', state: 'Uttarakhand', type: 'IIT' },
  { name: 'IIT Guwahati', city: 'Guwahati', state: 'Assam', type: 'IIT' },
  { name: 'IIT Hyderabad', city: 'Hyderabad', state: 'Telangana', type: 'IIT' },
  { name: 'IIT Indore', city: 'Indore', state: 'Madhya Pradesh', type: 'IIT' },
  { name: 'IIT BHU', city: 'Varanasi', state: 'Uttar Pradesh', type: 'IIT' },
  { name: 'IIT Dhanbad', city: 'Dhanbad', state: 'Jharkhand', type: 'IIT' },
  { name: 'IIT Bhubaneswar', city: 'Bhubaneswar', state: 'Odisha', type: 'IIT' },
  { name: 'IIT Gandhinagar', city: 'Gandhinagar', state: 'Gujarat', type: 'IIT' },
  { name: 'IIT Ropar', city: 'Rupnagar', state: 'Punjab', type: 'IIT' },
  { name: 'IIT Patna', city: 'Patna', state: 'Bihar', type: 'IIT' },
  { name: 'IIT Mandi', city: 'Mandi', state: 'Himachal Pradesh', type: 'IIT' },
  { name: 'IIT Jodhpur', city: 'Jodhpur', state: 'Rajasthan', type: 'IIT' },
  { name: 'IIT Tirupati', city: 'Tirupati', state: 'Andhra Pradesh', type: 'IIT' },
  { name: 'IIT Palakkad', city: 'Palakkad', state: 'Kerala', type: 'IIT' },
  { name: 'IIT Goa', city: 'Ponda', state: 'Goa', type: 'IIT' },
  { name: 'NIT Trichy', city: 'Tiruchirappalli', state: 'Tamil Nadu', type: 'NIT' },
  { name: 'NIT Surathkal', city: 'Mangaluru', state: 'Karnataka', type: 'NIT' },
  { name: 'NIT Warangal', city: 'Warangal', state: 'Telangana', type: 'NIT' },
  { name: 'NIT Calicut', city: 'Kozhikode', state: 'Kerala', type: 'NIT' },
  { name: 'NIT Rourkela', city: 'Rourkela', state: 'Odisha', type: 'NIT' },
  { name: 'NIT Durgapur', city: 'Durgapur', state: 'West Bengal', type: 'NIT' },
  { name: 'BITS Pilani', city: 'Pilani', state: 'Rajasthan', type: 'Private University' },
  { name: 'VIT Vellore', city: 'Vellore', state: 'Tamil Nadu', type: 'Private University' },
  { name: 'SRM Institute of Science and Technology', city: 'Chennai', state: 'Tamil Nadu', type: 'Private University' },
  { name: 'Manipal Institute of Technology', city: 'Manipal', state: 'Karnataka', type: 'Private Institute' },
  { name: 'Thapar Institute of Engineering and Technology', city: 'Patiala', state: 'Punjab', type: 'Private Institute' },
  { name: 'Jadavpur University', city: 'Kolkata', state: 'West Bengal', type: 'State University' },
  { name: 'Delhi Technological University', city: 'New Delhi', state: 'Delhi', type: 'State University' },
  { name: 'Anna University', city: 'Chennai', state: 'Tamil Nadu', type: 'State University' },
  { name: 'IIIT Hyderabad', city: 'Hyderabad', state: 'Telangana', type: 'IIIT' },
  { name: 'IIIT Bangalore', city: 'Bengaluru', state: 'Karnataka', type: 'IIIT' },
  { name: 'IIT Jammu', city: 'Jammu', state: 'Jammu and Kashmir', type: 'IIT' },
  { name: 'IIT Dharwad', city: 'Dharwad', state: 'Karnataka', type: 'IIT' },
  { name: 'IIT Bhilai', city: 'Bhilai', state: 'Chhattisgarh', type: 'IIT' },
  { name: 'NIT Kurukshetra', city: 'Kurukshetra', state: 'Haryana', type: 'NIT' },
  { name: 'NIT Allahabad', city: 'Prayagraj', state: 'Uttar Pradesh', type: 'NIT' },
  { name: 'NIT Jaipur', city: 'Jaipur', state: 'Rajasthan', type: 'NIT' },
  { name: 'NIT Bhopal', city: 'Bhopal', state: 'Madhya Pradesh', type: 'NIT' },
  { name: 'NIT Silchar', city: 'Silchar', state: 'Assam', type: 'NIT' },
  { name: 'NIT Hamirpur', city: 'Hamirpur', state: 'Himachal Pradesh', type: 'NIT' },
  { name: 'NIT Jalandhar', city: 'Jalandhar', state: 'Punjab', type: 'NIT' },
  { name: 'NIT Patna', city: 'Patna', state: 'Bihar', type: 'NIT' },
  { name: 'NIT Raipur', city: 'Raipur', state: 'Chhattisgarh', type: 'NIT' },
  { name: 'NIT Srinagar', city: 'Srinagar', state: 'Jammu and Kashmir', type: 'NIT' },
  { name: 'NIT Agartala', city: 'Agartala', state: 'Tripura', type: 'NIT' },
  { name: 'Amrita Vishwa Vidyapeetham', city: 'Coimbatore', state: 'Tamil Nadu', type: 'Private University' },
  { name: 'PSG College of Technology', city: 'Coimbatore', state: 'Tamil Nadu', type: 'Engineering College' },
  { name: 'College of Engineering Pune', city: 'Pune', state: 'Maharashtra', type: 'Government College' },
  { name: 'Netaji Subhas University of Technology', city: 'New Delhi', state: 'Delhi', type: 'State University' },
  { name: 'Institute of Chemical Technology', city: 'Mumbai', state: 'Maharashtra', type: 'Deemed University' },
  { name: 'IIIT Delhi', city: 'New Delhi', state: 'Delhi', type: 'IIIT' },
  { name: 'IIIT Allahabad', city: 'Prayagraj', state: 'Uttar Pradesh', type: 'IIIT' },
  { name: 'RV College of Engineering', city: 'Bengaluru', state: 'Karnataka', type: 'Engineering College' },
  { name: 'BMS College of Engineering', city: 'Bengaluru', state: 'Karnataka', type: 'Engineering College' },
  { name: 'Ramaiah Institute of Technology', city: 'Bengaluru', state: 'Karnataka', type: 'Engineering College' }
];

export const colleges = [
  { name: 'IIT Bombay', city: 'Mumbai', state: 'Maharashtra', type: 'Engineering', fee: 'INR 2.2L / yr', placement: '98%', salary: 'INR 25L', tag: '#1 NIRF' },
  { name: 'IIM Ahmedabad', city: 'Ahmedabad', state: 'Gujarat', type: 'Management', fee: 'INR 25L total', placement: '99%', salary: 'INR 32L', tag: '#1 Management' },
  { name: 'ISB Hyderabad', city: 'Hyderabad', state: 'Telangana', type: 'Business School', fee: 'INR 35L total', placement: '96%', salary: 'INR 28L', tag: 'Top Global B-School' },
  { name: 'University of Delhi', city: 'New Delhi', state: 'Delhi', type: 'University', fee: 'INR 20k - 1L / yr', placement: '92%', salary: 'INR 12L', tag: 'Historic Prestige' },
  { name: 'Andhra University', city: 'Visakhapatnam', state: 'Andhra Pradesh', type: 'University' },
  { name: 'Rajiv Gandhi University', city: 'Itanagar', state: 'Arunachal Pradesh', type: 'Central University' },
  { name: 'IIT Guwahati', city: 'Guwahati', state: 'Assam', type: 'Engineering' },
  { name: 'IIT Patna', city: 'Patna', state: 'Bihar', type: 'Engineering' },
  { name: 'NIT Raipur', city: 'Raipur', state: 'Chhattisgarh', type: 'Engineering' },
  { name: 'Goa University', city: 'Panaji', state: 'Goa', type: 'University' },
  { name: 'Ashoka University', city: 'Sonipat', state: 'Haryana', type: 'Liberal Arts' },
  { name: 'IIT Mandi', city: 'Mandi', state: 'Himachal Pradesh', type: 'Engineering' },
  { name: 'IIT Dhanbad', city: 'Dhanbad', state: 'Jharkhand', type: 'Engineering' },
  { name: 'Indian Institute of Science', city: 'Bengaluru', state: 'Karnataka', type: 'Research University' },
  { name: 'University of Kerala', city: 'Thiruvananthapuram', state: 'Kerala', type: 'University' },
  { name: 'IIT Indore', city: 'Indore', state: 'Madhya Pradesh', type: 'Engineering' },
  { name: 'Manipur University', city: 'Imphal', state: 'Manipur', type: 'Central University' },
  { name: 'IIM Shillong', city: 'Shillong', state: 'Meghalaya', type: 'Management' },
  { name: 'Mizoram University', city: 'Aizawl', state: 'Mizoram', type: 'Central University' },
  { name: 'Nagaland University', city: 'Lumami', state: 'Nagaland', type: 'Central University' },
  { name: 'IIT Bhubaneswar', city: 'Bhubaneswar', state: 'Odisha', type: 'Engineering' },
  { name: 'Panjab University', city: 'Chandigarh', state: 'Punjab', type: 'University' },
  { name: 'BITS Pilani', city: 'Pilani', state: 'Rajasthan', type: 'Engineering' },
  { name: 'Sikkim University', city: 'Gangtok', state: 'Sikkim', type: 'Central University' },
  { name: 'IIT Madras', city: 'Chennai', state: 'Tamil Nadu', type: 'Engineering' },
  { name: 'Tripura University', city: 'Agartala', state: 'Tripura', type: 'Central University' },
  { name: 'Banaras Hindu University', city: 'Varanasi', state: 'Uttar Pradesh', type: 'Central University' },
  { name: 'IIT Roorkee', city: 'Roorkee', state: 'Uttarakhand', type: 'Engineering' },
  { name: 'Jadavpur University', city: 'Kolkata', state: 'West Bengal', type: 'University' }
];

export const exams = [
  { name: 'JEE Main', stream: 'Engineering', level: 'National', mode: 'Online' },
  { name: 'JEE Advanced', stream: 'Engineering', level: 'National', mode: 'Online' },
  { name: 'NEET UG', stream: 'Medical', level: 'National', mode: 'Offline' },
  { name: 'CUET UG', stream: 'General', level: 'National', mode: 'Online' },
  { name: 'CAT', stream: 'Management', level: 'National', mode: 'Online' },
  { name: 'CLAT', stream: 'Law', level: 'National', mode: 'Offline' }
];

export const scholarships = [
  { name: 'National Scholarship Portal', eligibility: 'Merit and need based', amount: 'Varies' },
  { name: 'INSPIRE Scholarship', eligibility: 'Science students', amount: 'INR 80,000 / yr' },
  { name: 'AICTE Pragati Scholarship', eligibility: 'Women in technical education', amount: 'INR 50,000 / yr' },
  { name: 'Aditya Birla Scholarship', eligibility: 'Premier institute students', amount: 'Varies' }
];
